name: Nightmare
main: com.nightmare.Main
version: 1.0-release
api-version: 1.21
softdepend: [PlaceHolderAPI]
website: https://github.com/StevensBenavides/NightmareCore
description: 'Nightmare Core es un plugin que sube la dificultad de Minecraft al máximo.'

commands:
  nightmare:
    description: "Maneja el plugin Nightmare Core."
    usage: "/nightmare <category> <subcommand> | /nightmare <category>"

permissions:
  nightmare.reload:
    description: "Permite a un jugador recargar el plugin Nightmare Core."
    default: false